### PR TITLE
V8 engine (stla 1st commit)

### PR DESCRIPTION
**Pull request by stla**
This is my first pull request :)
I have pushed `R/engine-V8.R`. After building the package, two Rd files have been created and NAMESPACE and DESCRIPTION have been modified.
A link to an example is given.

Yours,
Stéphane

### CODE REVIEW

**Comment by yihui** [comment]
Thanks! I did not read the code very carefully, but I saw `eval(parse(text))`. That does not smell good to me... Anyway, personally I'm not very interested in including this engine in knitr. The runr package might be a better place to go: https://github.com/yihui/runr/issues/11

**Comment by stla** [comment]
One month ago you said you would prefer in knitr :) (or I am duped by my memory).
I used `eval(parse())` just to avoid to do a copy of the Javascript context. This is not necessary.

**Comment by yihui** [comment]
Sorry if I said that. Anyway, I guess I'm still not interested in this engine even if you manage to get rid of `eval(parse())`.

**Comment by stla** [comment]
Sorry @yihui  for not following-up this thread. I have a version of my V8 engine without `eval(parse())`, it is fine (but not perfect), but I just need to take the time to review it and to do the PR.

**Comment by yihui** [comment]
No worries. If you still plan to work on it, please submit the PR to https://github.com/yihui/runr/ instead. I'm planning a CRAN release for knitr, and that is why I'm looking at the existing old PRs and issues right now.

**Pull request closed without merging**
