### PR TITLE
New chunk option: `cache.rebuild`

### PR DESCRIPTION
**Pull request by zachary-foster**
From documentation ([pull request #996](https://github.com/yihui/knitr/pull/996)):

`cache.rebuild`: (`FALSE`) if `TRUE`, the chunk is evaluated even if `cache=TRUE`
  and no changes are made. This is useful when given an R code argument. 
  For example: `cache.rebuild=!file.exists("path/to/file.ext")`
  (see [#238](https://github.com/yihui/knitr/issues/238)).

I had a bit of trouble understanding everything that was going on in the code, but I think I got the gist of it. I basically used the idea that when `cache.rebuild = TRUE`, the code for loading and running the chunk would proceed as if the cache did not exist, but the parts of the code that saves the cache would remain unaffected. I tested this a couple different ways and it seems to accomplish the goal of  [#238](https://github.com/yihui/knitr/issues/238), but I cant guarantee its free of side effects without a greater understanding of the code. I can do some more rigorous testing, but it might help if you could point me towards some things it might break. Thanks!

### CODE REVIEW

**Comment by yihui** [comment]
This looks perfect. Could you merge the squash the four commits commits into one? https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md#pull-requests Thanks!

**Comment by yihui** [comment]
BTW, please also add a news item to https://github.com/yihui/knitr/blob/master/NEWS.md and yourself to https://github.com/yihui/knitr/blob/master/DESCRIPTION.

**Comment by yihui** [comment]
Due to the large amount of changes this weekend, it might be confusing for you to resolve the conflicts, so I just went ahead and merged the PR. Thanks!

**Comment by zachary-foster** [comment]
Thanks! I have been away from my computer for a few days. I forgot to look
for the contribution guidelines but i will follow them in the future.

Zach

On Sunday, April 19, 2015, Yihui Xie <notifications@github.com> wrote:

> Due to the large amount of changes this weekend, it might be confusing for
> you to resolve the conflicts, so I just went ahead and merged the PR.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yihui/knitr/pull/995#issuecomment-94299237>.
>


-- 
Zachary S.L. Foster, PhD Student
Oregon State University
USDA Agricultural Research Service
Horticultural Crops Research Lab
Corvallis, Oregon, USA
http://grunwaldlab.cgrb.oregonstate.edu/

**Pull request merged**
