### PR TITLE
Workaround for UTF-8 issues on Windows 7/8.

### PR DESCRIPTION
**Pull request by lgallindo**
Added and boolean parameter to knit(): lyx_compatible. If false, knit() will skip the call to correct_encode(). Functions that call knit() also received the extra parameter. The default value for the lyx_compatible parameter is TRUE, maintaining compatibility.

This provides a workaround for knitr falling back to Windows 1252 encoding on a Windows 7-8 platform correctly configured for UTF-8.

A proper solution would be review correct_encode(), but I'm not a LyX user and am afraid to break compatibility.

### CODE REVIEW

**Comment by lgallindo** [comment]
Related issue: https://github.com/yihui/knitr/issues/1546

**Comment by lgallindo** [comment]
Another related issue: https://github.com/yihui/knitr/issues/1343

**Comment by yihui** [comment]
@lgallindo I'd rather figure out how `correct_encode()` returned a wrong encoding instead of adding a new argument. You could help me in two possible ways: 1) answer my question above, or 2) provide an example with which I can reproduce the issue, so I can answer the question by myself. Thanks!

**Comment by lgallindo** [comment]
Ok. Will try to build a MWE tomorrow to check this.

**Comment by yihui** [comment]
Just a friendly ping :)

**Pull request closed without merging**
