### PR TITLE
add linebreaks before and after figures

### PR DESCRIPTION
**Pull request by atusy**
to solve #2032

### CODE REVIEW

**Comment by atusy** [comment]
I think we need 2 linebreaks before and after the plots so that they become individual blocks.
But this certainly breaks the test below.
Is it okay to update the test? @yihui

```
Error: (img_output("a.png") %==% "![](a.png)") is not TRUE
```

https://github.com/yihui/knitr/pull/2033/checks?check_run_id=3251862194#step:11:137

**Comment by yihui** [comment]
A breaking change is sometimes okay. I'm totally fine with breaking tests in this package. The much trickier and harder problem is to deal with is when the change breaks tests in other people's packages, over which I don't have control.

We can try and see how bad the breaking change is. Thanks!

**Comment by cderv** [comment]
I think this could break some outputs if this is no more possible to generate inline plots. The HTML output will be different (using inline `img` vs using figure environment) and this could break some specific styling maybe. As often with rmarkdown changes, I don't think this will concern R developer that have tests, but more users with their outputs. 

Also, I am trying to understand why we are finding this now. It feels to me like there is a regression somewhere. The current code here seems to assume that when `nocap` and inline image should be created. 
https://github.com/atusy/knitr/blob/46a48b1333e56802eab49851d861ca67b2929bdf/R/hooks-md.R#L58-L62

I did look deeply through it yet but this gets me thinking 😅 

Thanks for looking into it @atusy !

**Comment by atusy** [comment]
Closing as this PR is the duplicate of #1760

**Pull request closed without merging**
