### PR TITLE
Changes to allow rgl (and other?) graphics systems to work like base graphics

### PR DESCRIPTION
**Pull request by dmurdoch**
This patch is related to my comments on #1881 and my issue #1853, to allow `rgl` to work more seamlessly with `knitr`.  The idea is that, like base graphics, `rgl` has "high level" and "low level" commands to change the current display, and users typically only want to see output when a new high level command is run.

To do this, I needed to export two internal functions from `knitr`:  `wrap()` and `is_low_change()`.  I also needed to change `is_low_change()` to a generic function, so the test for low versus high could take place in `rgl`, and I introduced a new class name, `"knit_other_plot"` so that `knitr` could tell that my `rgl` graphics objects are actually plots that need handling.  The access to `wrap()` allows `rgl` graphics to efficiently share data:  if part of a plot has previously appeared, it won't be written to the HTML output.

This PR shouldn't have bad effects on anyone as far as I know.  The current development version of `rgl` on R-forge doesn't take advantage of the changes; it uses a complicated (and fragile, I worry) set of hooks to replace a bunch of code in `knitr`.  You can see the code that does work with this PR in https://github.com/dmurdoch/rgl branch `rglpatch`.

### CODE REVIEW

**Comment by dmurdoch** [comment]
Travis seems confused:  some checks have been sitting there all day, stuck at "Queued -- Build Created".

**Comment by dmurdoch** [comment]
Similar changes to these were merged into `pkgdown` in https://github.com/r-lib/pkgdown/pull/1548 and https://github.com/r-lib/downlit/pull/78 .  Some differences:

- In this PR, I exported `wrap` and `is_low_change`, but in the pkgdown changes the corresponding functions (`downlit:::replay_html` and `downlit:::is_low_change`) weren't exported. 

- The new class name `"knit_other_plot"` was called `"otherRecordedplot"`.

If you'd like one or both of those changes in this PR, I'd be happy to make them.

**Review by yihui — APPROVED** [review]
Looks good to me overall. I'll make some minor and doc changes before merging. Thanks!

**Comment by dmurdoch** [comment]
Great!

**Pull request merged**
