### PR TITLE
fix the Stata command line call

### PR DESCRIPTION
**Pull request by Hemken**
I've tested this on Windows.

Is there a good way to distinguish a Mac from other unix platforms?  The Stata command line for a Mac can be different (although it doesn't have to be), and the variation would be preferable I think.

I don't have a Mac to test on.

### CODE REVIEW

**Comment by yihui** [comment]
I'm not sure if @muschellij2 has a Mac to test it. To check if you are on Mac, you can use `Sys.info()[['sysname']] == 'Darwin'`.

BTW, I hope you can rebase your branch before submitting the pull request (to avoid the giant merge commit), or merge the two commits into one if you did not rebase. You can see more instructions from the contributing guide: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md#pull-requests Thanks!

**Comment by Hemken** [comment]
I'll figure out how to rebase.  Will I need to revert, rebase, then refix?  I pulled all your previous commits into my version, so the only thing left to merge is the one line of code, I think.

Finally got through to my linux server, and verified my fix there, so testing (such as it is) is complete.

**Comment by yihui** [comment]
You don't need to revert anything. You just need to remove the first commit of the two. I'm not sure what your GIT client is since you seem to be using Windows. You can probably `git rebase master~2 -i` in the command window, and delete the first commit. Then rebase your branch with my master branch using `git pull --rebase` (see the contributing guide).

**Comment by Hemken** [comment]
I think I see.  I didn't realize this request had 2 commits instead of 1.  I have a lot to learn!

**Comment by yihui** [comment]
Closing this one in favor of #1036.

**Pull request closed without merging**
