### PR TITLE
Stata engine, SAS output fixes

### PR DESCRIPTION
**Pull request by Hemken**
I have added a Stata engine.  This is another statistical language like SAS.

I made it possible to use the selective echo= chunk option with non-R engines.

I added some clean up for dealing with SAS and Stata output.

I've been working with these for a couple of weeks, and am pretty content with my changes.

Examples that use these changes are at
www.ssc.wisc.edu/~hemken/SASworkshops/SASWindows/Markdown/SASmarkdown.html
www.ssc.wisc.edu/~hemken/Stataworkshops/Stata%20and%20R%20Markdown/Stata.html

### CODE REVIEW

**Comment by yihui** [comment]
Thanks! I do not know much about SAS or Stata, but the examples look very nice.

@muschellij2 You might be interested in this stata engine since I remember you have asked a few times on Twitter.

**Comment by muschellij2** [comment]
Whoa- will look at ASAP.

**Comment by muschellij2** [comment]
@Hemken Can you use return results in inline text, like `stata `r(mean)'` after running summarize?

**Comment by muschellij2** [comment]
Looked at it and it seems as though it may be OS dependent, 
For example, I changed `statapath` to:
```
  statapath <- "/Applications/Stata/Stata.app/Contents/MacOS/Stata"
```
and it implemented the following command:
/Applications/Stata/Stata.app/Contents/MacOS/Stata  /q /e stataca4b62d3bc15.do
where /q /e I believe are Windows flags?

**Comment by yihui** [comment]
@muschellij2 Please feel free to submit a pull request if you know what the command-line arguments should be on Mac OS. Hint: check `Sys.info()[['sysname']]` for Mac, and `.Platform$OS.type == 'windows'` for Windows.

**Comment by muschellij2** [comment]
I think I do - I'll clone and try some of them and then send a pull

**Comment by muschellij2** [comment]
Umm how do you build this thing in RStudio?  Loaded .rproj and trying to build and reload and got 
Error in file.path(pkg, "man") : 
  argument "pkg" is missing, with no default

**Comment by yihui** [comment]
@muschellij2 You need to `install.packages('Rd2roxygen')` (and perhaps also `update.packages(ask = FALSE)`)

**Comment by Hemken** [comment]
Just thought I would verify for you that your cleanup of my code works fine.

At some point I should be able to test both SAS and Stata in our linux environment, but I haven't gotten there yet. Won't be able to test Mac OS.

On 03/31/15, John Muschelli  wrote:
> 
> Umm how do you build this thing in RStudio? Loaded .rproj and trying to build and reload and got 
> Error in file.path(pkg, "man") : 
> argument "pkg" is missing, with no default
> 
> &mdash;
> Reply to this email directly or view it on GitHub(https://github.com/yihui/knitr/pull/979#issuecomment-88345478).

--
Doug Hemken
4226I Social Science Bldg.

dehemken@wisc.edu
262-4327

To make a consulting appointment send me an email, or use the on-line scheduler:
https://calendar.wisc.edu/scheduling-assistant/public/profiles/PlRxCykH.html

**Comment by yihui** [comment]
@Hemken Thanks a lot!

**Pull request merged**
