### PR TITLE
handling of numeric rounding

### PR DESCRIPTION
**Pull request by numatt**
Proposed fix to match R numeric rounding standards. Addresses issue #1053.

Also includes updated and new tests for numeric rounding cases.

### CODE REVIEW

**Comment by numatt** [comment]
The rounding changes impact the precision of the results in the example files. Unfortunately, I'm unable to update the examples because the knit-all.R script crashes R on on my machine. Please feel free to review the proposed fix, and adopt something similar if you feel it's worthwhile. Thanks.

**Comment by yihui** [comment]
Thanks! I think this is a correct fix in theory. I cannot speak for other users, but personally I rarely find significant digits useful in practice. I often need to control the number of decimal places instead. I was abusing `getOption('digits')`.

**Comment by numatt** [comment]
Makes sense.

What bothered me was seeing different results in code chunks and inline chunks. I'm currently taking the Data Science series of courses on Coursera, and for new users at least, it's confusing and a bit frustrating when different packages inexplicably print out numerics in different formats. It makes it feel like you can't rely on the conventions or documentation.

I do tend to agree with your view that specifying decimal places may be more useful in practice. Would be nice to enable this in a way that doesn't abuse getOptions('digits'). :)

Regardless, thanks for the great package. I've been using it extensively.

**Comment by yihui** [comment]
I agree and I can see the frustration. Perhaps we can just replace `getOption('digits')` with something like `getOption('knitr.inline.digits', getOption('digits'))` so it is possible to configure the number of decimal places (fall back to the `digits` option if `knitr.inline.digits` is not specified).

**Comment by numatt** [comment]
Thanks. That provides a way of setting the decimal digits without abusing getOption('digits'). But, I think it doesn't provide an option of using the standard R behavior of rounding by significant digits. It would be nice to have a way to configure knitr so that printing a numeric in a code block gives the same results as printing it inline.

So, maybe something like `getOption('knitr.inline.rounddecimal', TRUE)`. The default would use the current rounding logic (rounding based on decimal places), and the alternative would be to round based on significant digits.

**Comment by yihui** [comment]
The `knitr.inline.rounddecimal` idea sounds good to me. If you are still interested in it, please feel free to update this PR. Thanks!

**Pull request closed without merging**
