### PR TITLE
export `wrap` generic

### PR DESCRIPTION
**Pull request by kbodwin**
Would you be willing to export this generic?  Happy to provide more info on how I'm using it if you're not sure.  Thank you!

### CODE REVIEW

**Comment by cderv** [comment]
Hi, 

I think this request is related to https://github.com/yihui/knitr/issues/1442 and `engine_output` has been adapted with an expert mode in order avoid exporting `wrap`. I guess it should support your usecase already, but happy to discuss it if you can give some details.

See `?knitr::engine_output` 
> For expert users, an advanced usage of this function is engine_output(options, out = LIST) where LIST is a list that has the same structure as the output of evaluate::evaluate(). In this case, the arguments code and extra are ignored, and the list is passed to an internal function knitr:::wrap() to return a character vector of final output.

Please tell us if it seems to fit your usage.
Hope it helps.

**Comment by kbodwin** [comment]
I got that to work, after some fiddling with the options.

It'd still be cool to have wrap exported, I think, for situations like this one where I just want the html wrapping, not necessarily something embedded in an engine.  But I'll leave that up to you all - my problem is solved. :)

Thank you!

**Comment by cderv** [comment]
Good it works for you too !
 
> It'd still be cool to have wrap exported, I think, for situations like this one where I just want the html wrapping, not necessarily something embedded in an engine. 

@yihui should an issue be opened to maybe reconsider this wrap export one day, and have a place to compile the different usage in the meantime maybe ?

**Comment by yihui** [comment]
I could consider exporting it after I see a convincing use case. I guess the S3 generic `knit_print()` (which has been exported) and the function `engine_output()` can do the job in most cases. `wrap()` is too low-level and messy (forgive my R skills 8 years ago), and I always hesitate when users request me to export it.

**Comment by cderv** [comment]
It makes sense. Thank you for the precisions !

**Pull request closed without merging**
