### PR TITLE
feat: add attr.source and attr.output as chunk options

### PR DESCRIPTION
**Pull request by atusy**
`attr.source` and `attr.output` allows specifying variety of attributes to code blocks, and thus are the sort of generalized versions of `class.source` and `class.output`.

When specifying `attr.*`, values must follow the format of Pandoc's fenced code attributes.
For example, classes are prefixed with ".", and ids with "#".

### Line numbering on code blocks with arbitary starting number

````
---
output:
  html_document: 
    highlight: pygments
    keep_md: true
---

```{r, class.source = "numberLines", attr.source = "startFrom='11'", class.output = "numberLines", attr.output = "startFrom='11'", results='hold'}
11
12
13
```
````

image

### Showing titles on code blocks 

````
```{css}
div.sourceCode[title]:before {content: attr(title); background: skyblue;}
```

```{r, attr.source = "title='density plot'"}
plot(density(iris[[1]]))
```
````

image

### CODE REVIEW

**Comment by atusy** [comment]
Travis CI fails here, but is passing on my forked repository.
`git push -f` doesn't help. Any ideas?

https://travis-ci.org/atusy/knitr/builds/529663129

**Comment by cderv** [comment]
I think the travis build fails here because there are some changes in some knitr-examples rendering. 
I am not sure it is linked to your PR, just some changes due to R 3.6.0 new behavior.

I will see what should be done in knitr-examples repo to support R 3.6.

**Comment by atusy** [comment]
Thanks @cderv .
I agree with your insight, and I noticed the issue is not restricted to my PR but to any branches including master.
Thus, I opened #1712 as a better place to discuss the issue.
Would you join there?

Le'ts see if my PR passes Travis CI after #1712 is solved.

**Comment by atusy** [comment]
The `knitr-examples` repo is fixed (https://github.com/yihui/knitr-examples/commit/c522631f36d06c4e7a3a295071ee236fcff0c611).
Now my PR passes tests!!

**Comment by atusy** [comment]
Thanks a lot. I have no problem with rewriting. I love simple things.

I reverted `tweak_bib.csv`.

**Comment by yihui** [comment]
Great. I'll try to modify your branch tomorrow.

**Pull request merged**
