### PR TITLE
Update engine.R

### PR DESCRIPTION
**Pull request by sumandoc**
Added [Perl 6](https://perl6.org/) support.

### CODE REVIEW

**Comment by yihui** [comment]
Thanks, but I think you can just do

    ```{perl, engine.path='perl6'}

https://yihui.name/knitr/options/#language-engines

**Comment by sumandoc** [comment]
Thanks but
```
```{perl, engine.path='perl6'}
```

**doesn't** work in **windows** !!

The reason for this I believe could be:

- While `perl -e 'print "Hello"'` works for **Perl 5**
- `perl6 -e 'print "Hello"'` **doesn't** work for **Perl 6**

**Comment by yihui** [comment]
What is the equivalent flag of `-e` in Perl 6?

**Comment by sumandoc** [comment]
Looks like its `-e` only.

- https://docs.perl6.org/programs/00-running
- https://github.com/WildYorkies/Perl6-One-Liners/blob/master/README.md

**Comment by yihui** [comment]
Since it is still `-e`, I don't know why `perl6 -e 'print "Hello"'` does not work on Windows. I don't know much about Perl, so you have to figure out what's wrong with `perl6 -e`.

**Comment by sumandoc** [comment]
This was a reason to add `perl6` as a new engine in this PR. ;)

**Comment by yihui** [comment]
Yes, I know that. I just don't like introducing new code when you can take advantage of existing code. If `perl6 -e` does not work, it is probably not my fault.

In general, I welcome pull requests, but I hesitate on accepting pull requests that introduce code that I'm not familiar with. Yes, this one is simple enough, but I just don't want to take the responsibility of answering possible future questions on `perl` vs `perl6`.

That said, knitr's language engine system is quite open, which means you can certainly modify it as you wish. `engine_output()` is an exported function, so you can just write your own engine function, and register it via `knitr::knit_engine$set(perl6 = whatever)`. You don't have to let me support it.

**Pull request closed without merging**
