### PR TITLE
Clojure support

### PR DESCRIPTION
**Pull request by kindlychung**
clojure support.
fixes in style.
example moved to knitr-example.

### CODE REVIEW

**Comment by kindlychung** [comment]
There is still a problem, clojure code block does not have a colored background in pdf and word documents, which is kind of irritating, but  html is working ok.

**Comment by robertzk** [comment]
I'm interested in this too; thanks! Can you backmerge master so yihui can merge it?

**Comment by yihui** [comment]
I have resolved the conflicts and merged it. Thanks @kindlychung, and sorry for having not merged it earlier...

**Comment by kindlychung** [comment]
Cool!

**Pull request merged**
